{
 "title": "Serve LLM Dashboard",
 "tags": [ "rayVersion:2.51.1" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "vllm_model_name",
    "label": "vLLM Model Name",
    "query": {
     "query": "label_values(ray_vllm:request_prompt_tokens_sum{}, model_name)"
    }
   },
   {
    "name": "workerid",
    "label": "Worker ID",
    "query": {
     "query": "label_values(ray_vllm:request_prompt_tokens_sum{}, WorkerId)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(ray_serve_deployment_request_counter_total{}, deployment)"
    }
   },
   { "name": "interval", "label": "Interval" }
  ]
 },
 "panels": [
  {
   "title": "QPS per vLLM worker",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (model_name, WorkerId, replica) (rate(ray_serve_deployment_request_counter_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", , deployment=~\"$deployment\"}[$interval]))",
     "legendFormat": "replica {{replica}}, worker {{WorkerId}}"
    },
    {
     "expr": "sum(rate(ray_serve_deployment_request_counter_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", , deployment=~\"$deployment\"}[$interval]))",
     "legendFormat": "Total QPS"
    }
   ]
  },
  {
   "title": "vLLM: Time Per Output Token Latency",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, model_name, WorkerId) (rate(ray_vllm_request_time_per_output_token_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P99 - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, model_name, WorkerId) (rate(ray_vllm_request_time_per_output_token_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P95 - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, model_name, WorkerId) (rate(ray_vllm_request_time_per_output_token_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P90 - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, model_name, WorkerId) (rate(ray_vllm_request_time_per_output_token_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P50 - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "(sum by(model_name, WorkerId) (rate(ray_vllm_request_time_per_output_token_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n/\nsum by(model_name, WorkerId) (rate(ray_vllm_request_time_per_output_token_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "Mean - {{model_name}} - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: Token Throughput",
   "type": "graph",
   "description": "Number of tokens processed per second",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "tokens/s" }
   ],
   "targets": [
    {
     "expr": "sum by (model_name, WorkerId) (rate(ray_vllm_request_prompt_tokens_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))",
     "legendFormat": "Prompt Tokens/Sec - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "sum by (model_name, WorkerId) (rate(ray_vllm_generation_tokens_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))",
     "legendFormat": "Generation Tokens/Sec - {{model_name}} - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: Time To First Token Latency",
   "type": "graph",
   "description": "P50, P90, P95, and P99 TTFT latency",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum by(model_name, WorkerId) (rate(ray_vllm_time_to_first_token_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n/\nsum by(model_name, WorkerId) (rate(ray_vllm_time_to_first_token_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "Average - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, model_name, WorkerId)(rate(ray_vllm_time_to_first_token_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P50 - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, model_name, WorkerId)(rate(ray_vllm_time_to_first_token_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P90 - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, model_name, WorkerId) (rate(ray_vllm_time_to_first_token_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P95 - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, model_name, WorkerId)(rate(ray_vllm_time_to_first_token_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P99 - {{model_name}} - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: Cache Utilization",
   "type": "graph",
   "description": "Percentage of used cache blocks by vLLM.",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (WorkerId) (ray_vllm_kv_cache_usage_perc{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", })",
     "legendFormat": "GPU Cache Usage - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: KV Cache Hit Rate",
   "type": "graph",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max(100 * (sum by (WorkerId) (rate(ray_vllm_prefix_cache_hits_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) / sum by (WorkerId) (rate(ray_vllm_prefix_cache_queries_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))))",
     "legendFormat": "Max Hit Rate"
    },
    {
     "expr": "min(100 * (sum by (WorkerId) (rate(ray_vllm_prefix_cache_hits_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) / sum by (WorkerId) (rate(ray_vllm_prefix_cache_queries_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))))",
     "legendFormat": "Min Hit Rate"
    },
    {
     "expr": "100 * (sum by (WorkerId) (rate(ray_vllm_prefix_cache_hits_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])) / sum by (WorkerId) (rate(ray_vllm_prefix_cache_queries_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "Hit Rate: worker {{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: E2E Request Latency",
   "type": "graph",
   "description": "Latency from request start to first token returned (in seconds).",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(model_name, WorkerId) (rate(ray_vllm_e2e_request_latency_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n/\nsum by(model_name, WorkerId) (rate(ray_vllm_e2e_request_latency_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))",
     "legendFormat": "Average - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, model_name, WorkerId) (rate(ray_vllm_e2e_request_latency_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P50 - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, model_name, WorkerId) (rate(ray_vllm_e2e_request_latency_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P90 - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, model_name, WorkerId) (rate(ray_vllm_e2e_request_latency_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P95 - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, model_name, WorkerId) (rate(ray_vllm_e2e_request_latency_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P99 - {{model_name}} - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: Scheduler State",
   "type": "graph",
   "description": "Number of requests in RUNNING, WAITING, and SWAPPED state",
   "gridPos": { "x": 12, "y": 24, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "Requests" }
   ],
   "targets": [
    {
     "expr": "ray_vllm_num_requests_running{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }",
     "legendFormat": "Num Running - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "ray_vllm_num_requests_swapped{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }",
     "legendFormat": "Num Swapped - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "ray_vllm_num_requests_waiting{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }",
     "legendFormat": "Num Waiting - {{model_name}} - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: Prompt Length",
   "type": "graph",
   "gridPos": { "x": 0, "y": 32, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, model_name, WorkerId) (rate(ray_vllm_request_prompt_tokens_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P50-{{model_name}}-{{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le, model_name, WorkerId) (rate(ray_vllm_request_prompt_tokens_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P90-{{model_name}}-{{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: Generation Length",
   "type": "graph",
   "gridPos": { "x": 12, "y": 32, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le, model_name, WorkerId) (rate(ray_vllm_request_generation_tokens_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P50-{{model_name}}-{{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le, model_name, WorkerId) (rate(ray_vllm_request_generation_tokens_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P90-{{model_name}}-{{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: Finish Reason",
   "type": "graph",
   "description": "Number of finished requests by their finish reason: either an EOS token was generated or the max sequence length was reached.",
   "gridPos": { "x": 0, "y": 48, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "Requests" }
   ],
   "targets": [
    {
     "expr": "sum by(finished_reason, model_name, WorkerId) (increase(ray_vllm_request_success_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))",
     "legendFormat": "{{finished_reason}} - {{model_name}} - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: Queue Time",
   "type": "graph",
   "gridPos": { "x": 12, "y": 48, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(model_name, WorkerId) (rate(ray_vllm_request_queue_time_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))",
     "legendFormat": "{{model_name}} - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: Requests Prefill and Decode Time",
   "type": "graph",
   "gridPos": { "x": 0, "y": 56, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(model_name, WorkerId) (rate(ray_vllm_request_decode_time_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))",
     "legendFormat": "Decode - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "sum by(model_name, WorkerId) (rate(ray_vllm_request_prefill_time_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))",
     "legendFormat": "Prefill - {{model_name}} - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: Max Generation Token in Sequence Group",
   "type": "graph",
   "gridPos": { "x": 12, "y": 56, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(model_name, WorkerId) (rate(ray_vllm_request_max_num_generation_tokens_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))",
     "legendFormat": "{{model_name}} - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "Tokens Last 24 Hours",
   "type": "stat",
   "gridPos": { "x": 0, "y": 64, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (model_name) (delta(ray_vllm_prompt_tokens_total{WorkerId=~\"$workerid\", }[1d])))",
     "legendFormat": "Input: {{model_name}}"
    },
    {
     "expr": "(sum by (model_name) (delta(ray_vllm_generation_tokens_total{WorkerId=~\"$workerid\", }[1d])))",
     "legendFormat": "Generated: {{model_name}}"
    }
   ]
  },
  {
   "title": "Tokens Last Hour",
   "type": "stat",
   "gridPos": { "x": 12, "y": 64, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(ray_vllm_prompt_tokens_total{WorkerId=~\"$workerid\", }[1h])",
     "legendFormat": "Input: {{model_name}}"
    },
    {
     "expr": "delta(ray_vllm_generation_tokens_total{WorkerId=~\"$workerid\", }[1h])",
     "legendFormat": "Generated: {{model_name}}"
    }
   ]
  },
  {
   "title": "Ratio Input:Generated Tokens Last 24 Hours",
   "type": "stat",
   "gridPos": { "x": 0, "y": 72, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_name) (delta(ray_vllm_prompt_tokens_total{WorkerId=~\"$workerid\", }[1d])) / sum by (model_name) (delta(ray_vllm_generation_tokens_total{WorkerId=~\"$workerid\", }[1d]))",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Distribution of Requests Per Model Last 24 Hours",
   "type": "piechart",
   "gridPos": { "x": 12, "y": 72, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "Requests" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_name) (delta(ray_vllm_request_success_total{WorkerId=~\"$workerid\", }[1d]))",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Peak Tokens Per Second Per Model Last 24 Hours",
   "type": "stat",
   "gridPos": { "x": 0, "y": 80, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum by (model_name) (rate(ray_vllm_generation_tokens_total{WorkerId=~\"$workerid\", }[2m]))[24h:1m])",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Tokens Per Model Last 24 Hours",
   "type": "stat",
   "gridPos": { "x": 12, "y": 80, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_name) (delta(ray_vllm_prompt_tokens_total{WorkerId=~\"$workerid\", }[1d])) + sum by (model_name) (delta(ray_vllm_generation_tokens_total{WorkerId=~\"$workerid\", }[1d]))",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Avg Total Tokens Per Request Last 7 Days",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 88, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (model_name) (delta(ray_vllm_prompt_tokens_total{WorkerId=~\"$workerid\", }[1w])) +\nsum by (model_name) (delta(ray_vllm_generation_tokens_total{WorkerId=~\"$workerid\", }[1w]))) / sum by (model_name) (delta(ray_vllm_request_success_total{WorkerId=~\"$workerid\", }[1w]))",
     "legendFormat": "{{ model_name}}"
    }
   ]
  },
  {
   "title": "Requests Per Model Last Week",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 88, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_name) (delta(ray_vllm_request_success_total{WorkerId=~\"$workerid\", }[1w]))",
     "legendFormat": "{{ model_name}}"
    }
   ]
  },
  {
   "title": "Tokens Per Model Last 7 Days",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 96, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_name) (delta(ray_vllm_prompt_tokens_total{WorkerId=~\"$workerid\", }[1w]))",
     "legendFormat": "In: {{ model_name}}"
    },
    {
     "expr": "sum by (model_name) (delta(ray_vllm_generation_tokens_total{WorkerId=~\"$workerid\", }[1w]))",
     "legendFormat": "Out: {{ model_name }}"
    }
   ]
  },
  {
   "title": "Avg Total Tokens Per Request Per Model Last 7 Days",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 96, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (model_name) (delta(ray_vllm_prompt_tokens_total{WorkerId=~\"$workerid\", }[1w])) + sum by (model_name) (delta(ray_vllm_generation_tokens_total{WorkerId=~\"$workerid\", }[1w])))/ sum by (model_name) (delta(ray_vllm_request_success_total{WorkerId=~\"$workerid\", }[1w]))",
     "legendFormat": "{{ model_name}}"
    }
   ]
  },
  {
   "title": "Tokens Per Request Per Model Last 7 Days",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 104, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_name) (delta(ray_vllm_prompt_tokens_total{WorkerId=~\"$workerid\", }[1w])) / sum by (model_name) (delta(ray_vllm_request_success_total{WorkerId=~\"$workerid\", }[1w]))",
     "legendFormat": "In: {{ model_name}}"
    },
    {
     "expr": "sum by (model_name) (delta(ray_vllm_generation_tokens_total{WorkerId=~\"$workerid\", }[1w])) / sum by (model_name) (delta(ray_vllm_request_success_total{WorkerId=~\"$workerid\", }[1w]))",
     "legendFormat": "Out: {{ model_name}}"
    }
   ]
  }
 ]
}